version: '3'
services:
  peer1:
    image: group14/blockchain
    ports:
      - "8081:8081"
    container_name: peer1
    
  peer2:
    image: group14/blockchain
    ports:
      - "8082:8082"
    container_name: peer2
  
  peer3:
    image: group14/blockchain
    ports:
      - "8083:8083"
    container_name: peer3

  peer4:
    image: group14/blockchain
    ports:
      - "8084:8084"
    container_name: peer4
    
